stages:
  - deploy

deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "nguyenngocbinhneu@gmail.com"
    - git config --global user.name "Nguyen Ngoc Binh"
    - git clone --mirror https://$CI_JOB_TOKEN@gitlab.com/nguyenngocbinh/ews.git
    - cd your_gitlab_repo.git
    - git remote add github https://$GITHUB_TOKEN@github.com/nguyenngocbinh/ews.git
    - git push --mirror github
  only:
    - master
