/*
 * Author: BinhNN2
 * Database: DB2
 * Project: CIC LONGLIST
 * PRIMARY KEY: RPT_DT, MSPHIEU, MA_CIC
 * PURPOSE: This procedure inserts data into TPBRM1.CIC_FEATURE_STORE_KHCN from CSO.CIC_RB04, CSO.CIC_RB06, and CSO.CIC_RB21
 *          based on the provided start_date and end_date parameters.
 * First date: 2024-07-17
 */
-- DROP PROCEDURE CIC_INIT;

CREATE OR REPLACE PROCEDURE CIC_INIT(
    IN start_date DATE,
    IN end_date DATE
)
LANGUAGE SQL
BEGIN
	DECLARE SQLSTATE CHAR(5);

	INSERT INTO TPBRM1.CIC_FEATURE_STORE_KHCN (RPT_DT, MSPHIEU, MA_CIC, CUSTOMER_TYPE)
	WITH t1 AS (
	SELECT RPT_DT, MSPHIEU, MA_CIC, 'KHCN' AS CUSTOMER_TYPE FROM CSO.CIC_RB04
	UNION
	SELECT RPT_DT, MSPHIEU, MA_CIC, 'KHCN' AS CUSTOMER_TYPE FROM CSO.CIC_RB06
	UNION
	SELECT RPT_DT, MSPHIEU, MA_CIC, 'KHCN' AS CUSTOMER_TYPE FROM CSO.CIC_RB21
	)
	SELECT RPT_DT, MSPHIEU, MA_CIC, CUSTOMER_TYPE 
	FROM t1
	WHERE MSPHIEU IS NOT NULL 
	AND MA_CIC IS NOT NULL 
	AND TO_DATE(RPT_DT, 'YYYYMMDD') BETWEEN start_date AND end_date;

COMMIT;

END;




