/*
* Author: HuyenDT14
* Database: DB2
* Project: CIC LONGLIST
* PRIMARY KEY: RPT_DT, MSPHIEU, MA_CIC
* First date: 2023-11-24
*/
CREATE OR replace PROCEDURE cic_rb06_ctnv_huyendt14 (IN start_date date, IN end_date date)
LANGUAGE SQL
BEGIN
   -- Step 1: Tao bang temp co TCTD 
   -- Create the global temporary table
DECLARE GLOBAL TEMPORARY TABLE SESSION.rb_ctnv (
	RPT_DT DATE
	,MSPHIEU VARCHAR(50)
	,MA_CIC VARCHAR(50)
	,NGAY_BAOCAO DATE
	,MA_TCTD VARCHAR(50)
	,TEN_TCTD VARCHAR(250)
	,LOAIVAY VARCHAR(50)
	,NHOMNO VARCHAR(50)
	,DUNO_VND DECIMAL(18, 2)
	,DUNO_USD DECIMAL(18, 2)
	,DUNO_USD_QUY_DOI DECIMAL(18, 2)
	,TONG_VND DECIMAL(18, 2)
	,TONG_USD DECIMAL(18, 2)
	,TONG_USD_QUY_DOI DECIMAL(18, 2)
	,TCTD VARCHAR(50)
	,TONG_DU_NO DECIMAL(18, 2)
	)
WITH REPLACE ON
COMMIT PRESERVE ROWS;



INSERT INTO   SESSION.rb_ctnv WITH t1 AS (
  SELECT *,(
      SELECT MID_RATE
FROM CSO.FCC_CYTB_RATES_HISTORY_OFFICIAL
WHERE CCY1 = 'USD'
AND RATE_DATE <= CAST(ctnv.RPT_DT AS date)
ORDER BY
          RATE_DATE DESC FETCH FIRST 1 ROWS ONLY) AS MID_RATE
FROM CSO.CIC_RB06_CTNV ctnv
WHERE TO_DATE(RPT_DT, 'YYYYMMDD') BETWEEN start_date AND end_date
) , t2 AS (
SELECT DISTINCT RPT_DT
	,MSPHIEU
	,MA_CIC
	,NGAY_BAOCAO
	,MA_TCTD
	,TEN_TCTD
	,LOAIVAY
	,NHOMNO
	,DUNO_VND
	,DUNO_USD
	,DUNO_USD * MID_RATE AS DUNO_USD_QUY_DOI
	,TONG_VND
	,TONG_USD
	,TONG_USD * MID_RATE AS TONG_USD_QUY_DOI
	,CASE 
		WHEN LENGTH(MA_TCTD) = 3
			THEN MA_TCTD
		ELSE SUBSTRING(ma_tctd, 3, 3)
		END AS TCTD

FROM t1)
SELECT *, TONG_VND + TONG_USD_QUY_DOI AS TONG_DU_NO
FROM t2;

-- Tao bien theo ma_tctd level
DROP TABLE IF EXISTS session.bank_level;


DECLARE GLOBAL TEMPORARY TABLE session.bank_level AS (
SELECT ma_cic, rpt_dt, msphieu, ma_tctd 
, sum(CASE WHEN loaivay = '01' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_SHORT_TERM 
, sum(CASE WHEN loaivay = '02' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_MEDIUM_TERM 
, sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_LONG_TERM 
, sum(CASE WHEN loaivay = '13' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OTHER 
, sum(CASE WHEN loaivay = '23' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OVERDUE 
, sum(TONG_DU_NO) AS LOAN_OS_TOTAL 
, sum(CASE WHEN nhomno = '01' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OD1 
, sum(CASE WHEN nhomno = '02' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OD2 
, sum(CASE WHEN nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OD12 
, sum(CASE WHEN nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OD345 
, sum(CASE WHEN nhomno = '01' THEN 1 ELSE 0 END) AS LOAN_CNT_OD1 
, sum(CASE WHEN nhomno = '02' THEN 1 ELSE 0 END) AS LOAN_CNT_OD2 
, sum(CASE WHEN nhomno IN ('01', '02') THEN 1 ELSE 0 END) AS LOAN_CNT_OD12 
, sum(CASE WHEN nhomno IN ('03', '04', '05') THEN 1 ELSE 0 END) AS LOAN_CNT_OD345 
, sum(CASE WHEN loaivay = '01' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_SHORT_OD1 
, sum(CASE WHEN loaivay = '01' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_SHORT_OD2 
, sum(CASE WHEN loaivay = '01' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_SHORT_OD12 
, sum(CASE WHEN loaivay = '01' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_SHORT_OD345 
, sum(CASE WHEN loaivay = '02' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_MEDIUM_OD1 
, sum(CASE WHEN loaivay = '02' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_MEDIUM_OD2 
, sum(CASE WHEN loaivay = '02' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_MEDIUM_OD12 
, sum(CASE WHEN loaivay = '02' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_MEDIUM_OD345 
, sum(CASE WHEN loaivay = '03' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_LONG_OD1 
, sum(CASE WHEN loaivay = '03' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_LONG_OD2 
, sum(CASE WHEN loaivay = '03' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_LONG_OD12 
, sum(CASE WHEN loaivay = '03' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_LONG_OD345 
, sum(CASE WHEN loaivay = '13' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OTHER_OD1 
, sum(CASE WHEN loaivay = '13' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OTHER_OD2 
, sum(CASE WHEN loaivay = '13' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OTHER_OD12 
, sum(CASE WHEN loaivay = '13' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END) AS LOAN_OS_OTHER_OD345
FROM session.rb_ctnv
GROUP BY
  ma_cic, rpt_dt, msphieu, ma_tctd) WITH DATA ORGANIZE BY ROW ;

-- Tao bien phai sinh min, max, avg, sum
DROP TABLE IF EXISTS session.cic_variables_part1;


DECLARE GLOBAL TEMPORARY TABLE cic_variables_part1 AS (
	SELECT ma_cic
	,rpt_dt
	,msphieu
	,sum(LOAN_OS_SHORT_TERM) AS LOAN_OS_SHORT_TERM_SUM
	,min(LOAN_OS_SHORT_TERM) AS LOAN_OS_SHORT_TERM_MIN
	,max(LOAN_OS_SHORT_TERM) AS LOAN_OS_SHORT_TERM_MAX
	,avg(LOAN_OS_SHORT_TERM) AS LOAN_OS_SHORT_TERM_AVG
	,sum(LOAN_OS_MEDIUM_TERM) AS LOAN_OS_MEDIUM_TERM_SUM
	,min(LOAN_OS_MEDIUM_TERM) AS LOAN_OS_MEDIUM_TERM_MIN
	,max(LOAN_OS_MEDIUM_TERM) AS LOAN_OS_MEDIUM_TERM_MAX
	,avg(LOAN_OS_MEDIUM_TERM) AS LOAN_OS_MEDIUM_TERM_AVG
	,sum(LOAN_OS_LONG_TERM) AS LOAN_OS_LONG_TERM_SUM
	,min(LOAN_OS_LONG_TERM) AS LOAN_OS_LONG_TERM_MIN
	,max(LOAN_OS_LONG_TERM) AS LOAN_OS_LONG_TERM_MAX
	,avg(LOAN_OS_LONG_TERM) AS LOAN_OS_LONG_TERM_AVG
	,sum(LOAN_OS_OTHER) AS LOAN_OS_OTHER_SUM
	,min(LOAN_OS_OTHER) AS LOAN_OS_OTHER_MIN
	,max(LOAN_OS_OTHER) AS LOAN_OS_OTHER_MAX
	,avg(LOAN_OS_OTHER) AS LOAN_OS_OTHER_AVG
	,sum(LOAN_OS_OVERDUE) AS LOAN_OS_OVERDUE_SUM
	,min(LOAN_OS_OVERDUE) AS LOAN_OS_OVERDUE_MIN
	,max(LOAN_OS_OVERDUE) AS LOAN_OS_OVERDUE_MAX
	,avg(LOAN_OS_OVERDUE) AS LOAN_OS_OVERDUE_AVG
	,sum(LOAN_OS_TOTAL) AS LOAN_OS_TOTAL_SUM
	,min(LOAN_OS_TOTAL) AS LOAN_OS_TOTAL_MIN
	,max(LOAN_OS_TOTAL) AS LOAN_OS_TOTAL_MAX
	,avg(LOAN_OS_TOTAL) AS LOAN_OS_TOTAL_AVG
	,sum(LOAN_OS_OD1) AS LOAN_OS_OD1_SUM
	,min(LOAN_OS_OD1) AS LOAN_OS_OD1_MIN
	,max(LOAN_OS_OD1) AS LOAN_OS_OD1_MAX
	,avg(LOAN_OS_OD1) AS LOAN_OS_OD1_AVG
	,sum(LOAN_OS_OD2) AS LOAN_OS_OD2_SUM
	,min(LOAN_OS_OD2) AS LOAN_OS_OD2_MIN
	,max(LOAN_OS_OD2) AS LOAN_OS_OD2_MAX
	,avg(LOAN_OS_OD2) AS LOAN_OS_OD2_AVG
	,sum(LOAN_OS_OD12) AS LOAN_OS_OD12_SUM
	,min(LOAN_OS_OD12) AS LOAN_OS_OD12_MIN
	,max(LOAN_OS_OD12) AS LOAN_OS_OD12_MAX
	,avg(LOAN_OS_OD12) AS LOAN_OS_OD12_AVG
	,sum(LOAN_OS_OD345) AS LOAN_OS_OD345_SUM
	,min(LOAN_OS_OD345) AS LOAN_OS_OD345_MIN
	,max(LOAN_OS_OD345) AS LOAN_OS_OD345_MAX
	,avg(LOAN_OS_OD345) AS LOAN_OS_OD345_AVG
	,sum(LOAN_CNT_OD1) AS LOAN_CNT_OD1_SUM
	,min(LOAN_CNT_OD1) AS LOAN_CNT_OD1_MIN
	,max(LOAN_CNT_OD1) AS LOAN_CNT_OD1_MAX
	,avg(LOAN_CNT_OD1) AS LOAN_CNT_OD1_AVG
	,sum(LOAN_CNT_OD2) AS LOAN_CNT_OD2_SUM
	,min(LOAN_CNT_OD2) AS LOAN_CNT_OD2_MIN
	,max(LOAN_CNT_OD2) AS LOAN_CNT_OD2_MAX
	,avg(LOAN_CNT_OD2) AS LOAN_CNT_OD2_AVG
	,sum(LOAN_CNT_OD12) AS LOAN_CNT_OD12_SUM
	,min(LOAN_CNT_OD12) AS LOAN_CNT_OD12_MIN
	,max(LOAN_CNT_OD12) AS LOAN_CNT_OD12_MAX
	,avg(LOAN_CNT_OD12) AS LOAN_CNT_OD12_AVG
	,sum(LOAN_CNT_OD345) AS LOAN_CNT_OD345_SUM
	,min(LOAN_CNT_OD345) AS LOAN_CNT_OD345_MIN
	,max(LOAN_CNT_OD345) AS LOAN_CNT_OD345_MAX
	,avg(LOAN_CNT_OD345) AS LOAN_CNT_OD345_AVG
	,sum(LOAN_OS_SHORT_OD1) AS LOAN_OS_SHORT_OD1_SUM
	,min(LOAN_OS_SHORT_OD1) AS LOAN_OS_SHORT_OD1_MIN
	,max(LOAN_OS_SHORT_OD1) AS LOAN_OS_SHORT_OD1_MAX
	,avg(LOAN_OS_SHORT_OD1) AS LOAN_OS_SHORT_OD1_AVG
	,sum(LOAN_OS_SHORT_OD2) AS LOAN_OS_SHORT_OD2_SUM
	,min(LOAN_OS_SHORT_OD2) AS LOAN_OS_SHORT_OD2_MIN
	,max(LOAN_OS_SHORT_OD2) AS LOAN_OS_SHORT_OD2_MAX
	,avg(LOAN_OS_SHORT_OD2) AS LOAN_OS_SHORT_OD2_AVG
	,sum(LOAN_OS_SHORT_OD12) AS LOAN_OS_SHORT_OD12_SUM
	,min(LOAN_OS_SHORT_OD12) AS LOAN_OS_SHORT_OD12_MIN
	,max(LOAN_OS_SHORT_OD12) AS LOAN_OS_SHORT_OD12_MAX
	,avg(LOAN_OS_SHORT_OD12) AS LOAN_OS_SHORT_OD12_AVG
	,sum(LOAN_OS_SHORT_OD345) AS LOAN_OS_SHORT_OD345_SUM
	,min(LOAN_OS_SHORT_OD345) AS LOAN_OS_SHORT_OD345_MIN
	,max(LOAN_OS_SHORT_OD345) AS LOAN_OS_SHORT_OD345_MAX
	,avg(LOAN_OS_SHORT_OD345) AS LOAN_OS_SHORT_OD345_AVG
	,sum(LOAN_OS_MEDIUM_OD1) AS LOAN_OS_MEDIUM_OD1_SUM
	,min(LOAN_OS_MEDIUM_OD1) AS LOAN_OS_MEDIUM_OD1_MIN
	,max(LOAN_OS_MEDIUM_OD1) AS LOAN_OS_MEDIUM_OD1_MAX
	,avg(LOAN_OS_MEDIUM_OD1) AS LOAN_OS_MEDIUM_OD1_AVG
	,sum(LOAN_OS_MEDIUM_OD2) AS LOAN_OS_MEDIUM_OD2_SUM
	,min(LOAN_OS_MEDIUM_OD2) AS LOAN_OS_MEDIUM_OD2_MIN
	,max(LOAN_OS_MEDIUM_OD2) AS LOAN_OS_MEDIUM_OD2_MAX
	,avg(LOAN_OS_MEDIUM_OD2) AS LOAN_OS_MEDIUM_OD2_AVG
	,sum(LOAN_OS_MEDIUM_OD12) AS LOAN_OS_MEDIUM_OD12_SUM
	,min(LOAN_OS_MEDIUM_OD12) AS LOAN_OS_MEDIUM_OD12_MIN
	,max(LOAN_OS_MEDIUM_OD12) AS LOAN_OS_MEDIUM_OD12_MAX
	,avg(LOAN_OS_MEDIUM_OD12) AS LOAN_OS_MEDIUM_OD12_AVG
	,sum(LOAN_OS_MEDIUM_OD345) AS LOAN_OS_MEDIUM_OD345_SUM
	,min(LOAN_OS_MEDIUM_OD345) AS LOAN_OS_MEDIUM_OD345_MIN
	,max(LOAN_OS_MEDIUM_OD345) AS LOAN_OS_MEDIUM_OD345_MAX
	,avg(LOAN_OS_MEDIUM_OD345) AS LOAN_OS_MEDIUM_OD345_AVG
	,sum(LOAN_OS_LONG_OD1) AS LOAN_OS_LONG_OD1_SUM
	,min(LOAN_OS_LONG_OD1) AS LOAN_OS_LONG_OD1_MIN
	,max(LOAN_OS_LONG_OD1) AS LOAN_OS_LONG_OD1_MAX
	,avg(LOAN_OS_LONG_OD1) AS LOAN_OS_LONG_OD1_AVG
	,sum(LOAN_OS_LONG_OD2) AS LOAN_OS_LONG_OD2_SUM
	,min(LOAN_OS_LONG_OD2) AS LOAN_OS_LONG_OD2_MIN
	,max(LOAN_OS_LONG_OD2) AS LOAN_OS_LONG_OD2_MAX
	,avg(LOAN_OS_LONG_OD2) AS LOAN_OS_LONG_OD2_AVG
	,sum(LOAN_OS_LONG_OD12) AS LOAN_OS_LONG_OD12_SUM
	,min(LOAN_OS_LONG_OD12) AS LOAN_OS_LONG_OD12_MIN
	,max(LOAN_OS_LONG_OD12) AS LOAN_OS_LONG_OD12_MAX
	,avg(LOAN_OS_LONG_OD12) AS LOAN_OS_LONG_OD12_AVG
	,sum(LOAN_OS_LONG_OD345) AS LOAN_OS_LONG_OD345_SUM
	,min(LOAN_OS_LONG_OD345) AS LOAN_OS_LONG_OD345_MIN
	,max(LOAN_OS_LONG_OD345) AS LOAN_OS_LONG_OD345_MAX
	,avg(LOAN_OS_LONG_OD345) AS LOAN_OS_LONG_OD345_AVG
	,sum(LOAN_OS_OTHER_OD1) AS LOAN_OS_OTHER_OD1_SUM
	,min(LOAN_OS_OTHER_OD1) AS LOAN_OS_OTHER_OD1_MIN
	,max(LOAN_OS_OTHER_OD1) AS LOAN_OS_OTHER_OD1_MAX
	,avg(LOAN_OS_OTHER_OD1) AS LOAN_OS_OTHER_OD1_AVG
	,sum(LOAN_OS_OTHER_OD2) AS LOAN_OS_OTHER_OD2_SUM
	,min(LOAN_OS_OTHER_OD2) AS LOAN_OS_OTHER_OD2_MIN
	,max(LOAN_OS_OTHER_OD2) AS LOAN_OS_OTHER_OD2_MAX
	,avg(LOAN_OS_OTHER_OD2) AS LOAN_OS_OTHER_OD2_AVG
	,sum(LOAN_OS_OTHER_OD12) AS LOAN_OS_OTHER_OD12_SUM
	,min(LOAN_OS_OTHER_OD12) AS LOAN_OS_OTHER_OD12_MIN
	,max(LOAN_OS_OTHER_OD12) AS LOAN_OS_OTHER_OD12_MAX
	,avg(LOAN_OS_OTHER_OD12) AS LOAN_OS_OTHER_OD12_AVG
	,sum(LOAN_OS_OTHER_OD345) AS LOAN_OS_OTHER_OD345_SUM
	,min(LOAN_OS_OTHER_OD345) AS LOAN_OS_OTHER_OD345_MIN
	,max(LOAN_OS_OTHER_OD345) AS LOAN_OS_OTHER_OD345_MAX
	,avg(LOAN_OS_OTHER_OD345) AS LOAN_OS_OTHER_OD345_AVG 
	FROM session.bank_level 
	GROUP BY ma_cic	,rpt_dt	,msphieu
	)
WITH DATA ORGANIZE BY ROW;


-- Tao bien theo msphieu level
DROP TABLE IF EXISTS session.cic_variables_part2;


DECLARE GLOBAL TEMPORARY TABLE cic_variables_part2 AS (
SELECT ma_cic, rpt_dt, MSPHIEU 
, sum(CASE WHEN loaivay = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_SHORT_TERM_RATIO 
, sum(CASE WHEN loaivay = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_MEDIUM_TERM_RATIO 
, sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_LONG_TERM_RATIO 
, sum(CASE WHEN loaivay = '13' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OTHER_RATIO 
, sum(CASE WHEN loaivay = '23' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OVERDUE_RATIO 
, sum(CASE WHEN loaivay = '01' THEN 1 ELSE 0 END) AS LOAN_CT_SHORT_TERM 
, sum(CASE WHEN loaivay = '02' THEN 1 ELSE 0 END) AS LOAN_CT_MEDIUM_TERM 
, sum(CASE WHEN loaivay = '03' THEN 1 ELSE 0 END) AS LOAN_CT_LONG_TERM 
, sum(CASE WHEN loaivay = '13' THEN 1 ELSE 0 END) AS LOAN_CT_OTHER 
, sum(CASE WHEN loaivay = '23' THEN 1 ELSE 0 END) AS LOAN_CT_OVERDUE 
, count(1) AS LOAN_CT_TOTAL 
, sum(CASE WHEN loaivay = '01' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CT_SHORT_TERM_RATIO 
, sum(CASE WHEN loaivay = '02' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CT_MEDIUM_TERM_RATIO 
, sum(CASE WHEN loaivay = '03' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CT_LONG_TERM_RATIO 
, sum(CASE WHEN loaivay = '13' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CT_OTHER_RATIO 
, sum(CASE WHEN loaivay = '23' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CT_OVERDUE_RATIO 
, sum(CASE WHEN nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OD1_RATIO 
, sum(CASE WHEN nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OD2_RATIO 
, sum(CASE WHEN nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OD12_RATIO 
, sum(CASE WHEN nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OD345_RATIO 
, sum(CASE WHEN nhomno = '01' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CNT_OD1_RATIO 
, sum(CASE WHEN nhomno = '02' THEN 1 ELSE 0 END)/ count(1) AS LOAN_CNT_OD2_RATIO 
, sum(CASE WHEN nhomno IN ('01', '02') THEN 1 ELSE 0 END)/ count(1) AS LOAN_CNT_OD12_RATIO 
, sum(CASE WHEN nhomno IN ('03', '04', '05') THEN 1 ELSE 0 END)/ count(1) AS LOAN_CNT_OD345_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_SHORT_OD1_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_SHORT_OD2_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_SHORT_OD12_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_SHORT_OD345_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '01' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_SHORT_OD1_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '01' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_SHORT_OD2_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '01' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_SHORT_OD12_RATIO 
, sum(CASE WHEN loaivay = '01' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '01' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_SHORT_OD345_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_MEDIUM_OD1_TOTAL_RATIO , sum(CASE WHEN loaivay = '02' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_MEDIUM_OD2_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_MEDIUM_OD12_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_MEDIUM_OD345_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '02' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_MEDIUM_OD1_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '02' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_MEDIUM_OD2_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '02' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_MEDIUM_OD12_RATIO 
, sum(CASE WHEN loaivay = '02' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '02' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_MEDIUM_OD345_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_LONG_OD1_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_LONG_OD2_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_LONG_OD12_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_LONG_OD345_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_LONG_OD1_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_LONG_OD2_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_LONG_OD12_RATIO 
, sum(CASE WHEN loaivay = '03' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_LONG_OD345_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OTHER_OD1_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OTHER_OD2_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OTHER_OD12_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(TONG_DU_NO) AS LOAN_OS_OTHER_OD345_TOTAL_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno = '01' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_OTHER_OD1_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno = '02' THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_OTHER_OD2_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno IN ('01', '02') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_OTHER_OD12_RATIO 
, sum(CASE WHEN loaivay = '13' AND nhomno IN ('03', '04', '05') THEN TONG_DU_NO ELSE 0 END)/ sum(CASE WHEN loaivay = '03' THEN TONG_DU_NO ELSE NULL END) AS LOAN_OS_OTHER_OD345_RATIO
FROM session.rb_ctnv
GROUP BY
  ma_cic, rpt_dt, MSPHIEU) WITH DATA ORGANIZE BY ROW;


UPDATE TPBRM1.CIC_FEATURE_STORE_KHCN
SET LOAN_OS_SHORT_TERM_SUM = t1.LOAN_OS_SHORT_TERM_SUM
	,LOAN_OS_SHORT_TERM_MIN = t1.LOAN_OS_SHORT_TERM_MIN
	,LOAN_OS_SHORT_TERM_MAX = t1.LOAN_OS_SHORT_TERM_MAX
	,LOAN_OS_SHORT_TERM_AVG = t1.LOAN_OS_SHORT_TERM_AVG
	,LOAN_OS_MEDIUM_TERM_SUM = t1.LOAN_OS_MEDIUM_TERM_SUM
	,LOAN_OS_MEDIUM_TERM_MIN = t1.LOAN_OS_MEDIUM_TERM_MIN
	,LOAN_OS_MEDIUM_TERM_MAX = t1.LOAN_OS_MEDIUM_TERM_MAX
	,LOAN_OS_MEDIUM_TERM_AVG = t1.LOAN_OS_MEDIUM_TERM_AVG
	,LOAN_OS_LONG_TERM_SUM = t1.LOAN_OS_LONG_TERM_SUM
	,LOAN_OS_LONG_TERM_MIN = t1.LOAN_OS_LONG_TERM_MIN
	,LOAN_OS_LONG_TERM_MAX = t1.LOAN_OS_LONG_TERM_MAX
	,LOAN_OS_LONG_TERM_AVG = t1.LOAN_OS_LONG_TERM_AVG
	,LOAN_OS_OTHER_SUM = t1.LOAN_OS_OTHER_SUM
	,LOAN_OS_OTHER_MIN = t1.LOAN_OS_OTHER_MIN
	,LOAN_OS_OTHER_MAX = t1.LOAN_OS_OTHER_MAX
	,LOAN_OS_OTHER_AVG = t1.LOAN_OS_OTHER_AVG
	,LOAN_OS_OVERDUE_SUM = t1.LOAN_OS_OVERDUE_SUM
	,LOAN_OS_OVERDUE_MIN = t1.LOAN_OS_OVERDUE_MIN
	,LOAN_OS_OVERDUE_MAX = t1.LOAN_OS_OVERDUE_MAX
	,LOAN_OS_OVERDUE_AVG = t1.LOAN_OS_OVERDUE_AVG
	,LOAN_OS_TOTAL_SUM = t1.LOAN_OS_TOTAL_SUM
	,LOAN_OS_TOTAL_MIN = t1.LOAN_OS_TOTAL_MIN
	,LOAN_OS_TOTAL_MAX = t1.LOAN_OS_TOTAL_MAX
	,LOAN_OS_TOTAL_AVG = t1.LOAN_OS_TOTAL_AVG
	,LOAN_OS_OD1_SUM = t1.LOAN_OS_OD1_SUM
	,LOAN_OS_OD1_MIN = t1.LOAN_OS_OD1_MIN
	,LOAN_OS_OD1_MAX = t1.LOAN_OS_OD1_MAX
	,LOAN_OS_OD1_AVG = t1.LOAN_OS_OD1_AVG
	,LOAN_OS_OD2_SUM = t1.LOAN_OS_OD2_SUM
	,LOAN_OS_OD2_MIN = t1.LOAN_OS_OD2_MIN
	,LOAN_OS_OD2_MAX = t1.LOAN_OS_OD2_MAX
	,LOAN_OS_OD2_AVG = t1.LOAN_OS_OD2_AVG
	,LOAN_OS_OD12_SUM = t1.LOAN_OS_OD12_SUM
	,LOAN_OS_OD12_MIN = t1.LOAN_OS_OD12_MIN
	,LOAN_OS_OD12_MAX = t1.LOAN_OS_OD12_MAX
	,LOAN_OS_OD12_AVG = t1.LOAN_OS_OD12_AVG
	,LOAN_OS_OD345_SUM = t1.LOAN_OS_OD345_SUM
	,LOAN_OS_OD345_MIN = t1.LOAN_OS_OD345_MIN
	,LOAN_OS_OD345_MAX = t1.LOAN_OS_OD345_MAX
	,LOAN_OS_OD345_AVG = t1.LOAN_OS_OD345_AVG
	,LOAN_CNT_OD1_SUM = t1.LOAN_CNT_OD1_SUM
	,LOAN_CNT_OD1_MIN = t1.LOAN_CNT_OD1_MIN
	,LOAN_CNT_OD1_MAX = t1.LOAN_CNT_OD1_MAX
	,LOAN_CNT_OD1_AVG = t1.LOAN_CNT_OD1_AVG
	,LOAN_CNT_OD2_SUM = t1.LOAN_CNT_OD2_SUM
	,LOAN_CNT_OD2_MIN = t1.LOAN_CNT_OD2_MIN
	,LOAN_CNT_OD2_MAX = t1.LOAN_CNT_OD2_MAX
	,LOAN_CNT_OD2_AVG = t1.LOAN_CNT_OD2_AVG
	,LOAN_CNT_OD12_SUM = t1.LOAN_CNT_OD12_SUM
	,LOAN_CNT_OD12_MIN = t1.LOAN_CNT_OD12_MIN
	,LOAN_CNT_OD12_MAX = t1.LOAN_CNT_OD12_MAX
	,LOAN_CNT_OD12_AVG = t1.LOAN_CNT_OD12_AVG
	,LOAN_CNT_OD345_SUM = t1.LOAN_CNT_OD345_SUM
	,LOAN_CNT_OD345_MIN = t1.LOAN_CNT_OD345_MIN
	,LOAN_CNT_OD345_MAX = t1.LOAN_CNT_OD345_MAX
	,LOAN_CNT_OD345_AVG = t1.LOAN_CNT_OD345_AVG
	,LOAN_OS_SHORT_OD1_SUM = t1.LOAN_OS_SHORT_OD1_SUM
	,LOAN_OS_SHORT_OD1_MIN = t1.LOAN_OS_SHORT_OD1_MIN
	,LOAN_OS_SHORT_OD1_MAX = t1.LOAN_OS_SHORT_OD1_MAX
	,LOAN_OS_SHORT_OD1_AVG = t1.LOAN_OS_SHORT_OD1_AVG
	,LOAN_OS_SHORT_OD2_SUM = t1.LOAN_OS_SHORT_OD2_SUM
	,LOAN_OS_SHORT_OD2_MIN = t1.LOAN_OS_SHORT_OD2_MIN
	,LOAN_OS_SHORT_OD2_MAX = t1.LOAN_OS_SHORT_OD2_MAX
	,LOAN_OS_SHORT_OD2_AVG = t1.LOAN_OS_SHORT_OD2_AVG
	,LOAN_OS_SHORT_OD12_SUM = t1.LOAN_OS_SHORT_OD12_SUM
	,LOAN_OS_SHORT_OD12_MIN = t1.LOAN_OS_SHORT_OD12_MIN
	,LOAN_OS_SHORT_OD12_MAX = t1.LOAN_OS_SHORT_OD12_MAX
	,LOAN_OS_SHORT_OD12_AVG = t1.LOAN_OS_SHORT_OD12_AVG
	,LOAN_OS_SHORT_OD345_SUM = t1.LOAN_OS_SHORT_OD345_SUM
	,LOAN_OS_SHORT_OD345_MIN = t1.LOAN_OS_SHORT_OD345_MIN
	,LOAN_OS_SHORT_OD345_MAX = t1.LOAN_OS_SHORT_OD345_MAX
	,LOAN_OS_SHORT_OD345_AVG = t1.LOAN_OS_SHORT_OD345_AVG
	,LOAN_OS_MEDIUM_OD1_SUM = t1.LOAN_OS_MEDIUM_OD1_SUM
	,LOAN_OS_MEDIUM_OD1_MIN = t1.LOAN_OS_MEDIUM_OD1_MIN
	,LOAN_OS_MEDIUM_OD1_MAX = t1.LOAN_OS_MEDIUM_OD1_MAX
	,LOAN_OS_MEDIUM_OD1_AVG = t1.LOAN_OS_MEDIUM_OD1_AVG
	,LOAN_OS_MEDIUM_OD2_SUM = t1.LOAN_OS_MEDIUM_OD2_SUM
	,LOAN_OS_MEDIUM_OD2_MIN = t1.LOAN_OS_MEDIUM_OD2_MIN
	,LOAN_OS_MEDIUM_OD2_MAX = t1.LOAN_OS_MEDIUM_OD2_MAX
	,LOAN_OS_MEDIUM_OD2_AVG = t1.LOAN_OS_MEDIUM_OD2_AVG
	,LOAN_OS_MEDIUM_OD12_SUM = t1.LOAN_OS_MEDIUM_OD12_SUM
	,LOAN_OS_MEDIUM_OD12_MIN = t1.LOAN_OS_MEDIUM_OD12_MIN
	,LOAN_OS_MEDIUM_OD12_MAX = t1.LOAN_OS_MEDIUM_OD12_MAX
	,LOAN_OS_MEDIUM_OD12_AVG = t1.LOAN_OS_MEDIUM_OD12_AVG
	,LOAN_OS_MEDIUM_OD345_SUM = t1.LOAN_OS_MEDIUM_OD345_SUM
	,LOAN_OS_MEDIUM_OD345_MIN = t1.LOAN_OS_MEDIUM_OD345_MIN
	,LOAN_OS_MEDIUM_OD345_MAX = t1.LOAN_OS_MEDIUM_OD345_MAX
	,LOAN_OS_MEDIUM_OD345_AVG = t1.LOAN_OS_MEDIUM_OD345_AVG
	,LOAN_OS_LONG_OD1_SUM = t1.LOAN_OS_LONG_OD1_SUM
	,LOAN_OS_LONG_OD1_MIN = t1.LOAN_OS_LONG_OD1_MIN
	,LOAN_OS_LONG_OD1_MAX = t1.LOAN_OS_LONG_OD1_MAX
	,LOAN_OS_LONG_OD1_AVG = t1.LOAN_OS_LONG_OD1_AVG
	,LOAN_OS_LONG_OD2_SUM = t1.LOAN_OS_LONG_OD2_SUM
	,LOAN_OS_LONG_OD2_MIN = t1.LOAN_OS_LONG_OD2_MIN
	,LOAN_OS_LONG_OD2_MAX = t1.LOAN_OS_LONG_OD2_MAX
	,LOAN_OS_LONG_OD2_AVG = t1.LOAN_OS_LONG_OD2_AVG
	,LOAN_OS_LONG_OD12_SUM = t1.LOAN_OS_LONG_OD12_SUM
	,LOAN_OS_LONG_OD12_MIN = t1.LOAN_OS_LONG_OD12_MIN
	,LOAN_OS_LONG_OD12_MAX = t1.LOAN_OS_LONG_OD12_MAX
	,LOAN_OS_LONG_OD12_AVG = t1.LOAN_OS_LONG_OD12_AVG
	,LOAN_OS_LONG_OD345_SUM = t1.LOAN_OS_LONG_OD345_SUM
	,LOAN_OS_LONG_OD345_MIN = t1.LOAN_OS_LONG_OD345_MIN
	,LOAN_OS_LONG_OD345_MAX = t1.LOAN_OS_LONG_OD345_MAX
	,LOAN_OS_LONG_OD345_AVG = t1.LOAN_OS_LONG_OD345_AVG
	,LOAN_OS_OTHER_OD1_SUM = t1.LOAN_OS_OTHER_OD1_SUM
	,LOAN_OS_OTHER_OD1_MIN = t1.LOAN_OS_OTHER_OD1_MIN
	,LOAN_OS_OTHER_OD1_MAX = t1.LOAN_OS_OTHER_OD1_MAX
	,LOAN_OS_OTHER_OD1_AVG = t1.LOAN_OS_OTHER_OD1_AVG
	,LOAN_OS_OTHER_OD2_SUM = t1.LOAN_OS_OTHER_OD2_SUM
	,LOAN_OS_OTHER_OD2_MIN = t1.LOAN_OS_OTHER_OD2_MIN
	,LOAN_OS_OTHER_OD2_MAX = t1.LOAN_OS_OTHER_OD2_MAX
	,LOAN_OS_OTHER_OD2_AVG = t1.LOAN_OS_OTHER_OD2_AVG
	,LOAN_OS_OTHER_OD12_SUM = t1.LOAN_OS_OTHER_OD12_SUM
	,LOAN_OS_OTHER_OD12_MIN = t1.LOAN_OS_OTHER_OD12_MIN
	,LOAN_OS_OTHER_OD12_MAX = t1.LOAN_OS_OTHER_OD12_MAX
	,LOAN_OS_OTHER_OD12_AVG = t1.LOAN_OS_OTHER_OD12_AVG
	,LOAN_OS_OTHER_OD345_SUM = t1.LOAN_OS_OTHER_OD345_SUM
	,LOAN_OS_OTHER_OD345_MIN = t1.LOAN_OS_OTHER_OD345_MIN
	,LOAN_OS_OTHER_OD345_MAX = t1.LOAN_OS_OTHER_OD345_MAX
	,LOAN_OS_OTHER_OD345_AVG = t1.LOAN_OS_OTHER_OD345_AVG
FROM session.cic_variables_part1 t1
WHERE CIC_FEATURE_STORE_KHCN.MA_CIC = t1.ma_cic AND CIC_FEATURE_STORE_KHCN.MSPHIEU = t1.msphieu AND CIC_FEATURE_STORE_KHCN.RPT_DT = t1.rpt_dt;



UPDATE TPBRM1.CIC_FEATURE_STORE_KHCN
SET LOAN_OS_SHORT_TERM_RATIO = t1.LOAN_OS_SHORT_TERM_RATIO
	,LOAN_OS_MEDIUM_TERM_RATIO = t1.LOAN_OS_MEDIUM_TERM_RATIO
	,LOAN_OS_LONG_TERM_RATIO = t1.LOAN_OS_LONG_TERM_RATIO
	,LOAN_OS_OTHER_RATIO = t1.LOAN_OS_OTHER_RATIO
	,LOAN_OS_OVERDUE_RATIO = t1.LOAN_OS_OVERDUE_RATIO
	,LOAN_CT_SHORT_TERM = t1.LOAN_CT_SHORT_TERM
	,LOAN_CT_MEDIUM_TERM = t1.LOAN_CT_MEDIUM_TERM
	,LOAN_CT_LONG_TERM = t1.LOAN_CT_LONG_TERM
	,LOAN_CT_OTHER = t1.LOAN_CT_OTHER
	,LOAN_CT_OVERDUE = t1.LOAN_CT_OVERDUE
	,LOAN_CT_TOTAL = t1.LOAN_CT_TOTAL
	,LOAN_CT_SHORT_TERM_RATIO = t1.LOAN_CT_SHORT_TERM_RATIO
	,LOAN_CT_MEDIUM_TERM_RATIO = t1.LOAN_CT_MEDIUM_TERM_RATIO
	,LOAN_CT_LONG_TERM_RATIO = t1.LOAN_CT_LONG_TERM_RATIO
	,LOAN_CT_OTHER_RATIO = t1.LOAN_CT_OTHER_RATIO
	,LOAN_CT_OVERDUE_RATIO = t1.LOAN_CT_OVERDUE_RATIO
	,LOAN_OS_OD1_RATIO = t1.LOAN_OS_OD1_RATIO
	,LOAN_OS_OD2_RATIO = t1.LOAN_OS_OD2_RATIO
	,LOAN_OS_OD12_RATIO = t1.LOAN_OS_OD12_RATIO
	,LOAN_OS_OD345_RATIO = t1.LOAN_OS_OD345_RATIO
	,LOAN_CNT_OD1_RATIO = t1.LOAN_CNT_OD1_RATIO
	,LOAN_CNT_OD2_RATIO = t1.LOAN_CNT_OD2_RATIO
	,LOAN_CNT_OD12_RATIO = t1.LOAN_CNT_OD12_RATIO
	,LOAN_CNT_OD345_RATIO = t1.LOAN_CNT_OD345_RATIO
	,LOAN_OS_SHORT_OD1_TOTAL_RATIO = t1.LOAN_OS_SHORT_OD1_TOTAL_RATIO
	,LOAN_OS_SHORT_OD2_TOTAL_RATIO = t1.LOAN_OS_SHORT_OD2_TOTAL_RATIO
	,LOAN_OS_SHORT_OD12_TOTAL_RATIO = t1.LOAN_OS_SHORT_OD12_TOTAL_RATIO
	,LOAN_OS_SHORT_OD345_TOTAL_RATIO = t1.LOAN_OS_SHORT_OD345_TOTAL_RATIO
	,LOAN_OS_SHORT_OD1_RATIO = t1.LOAN_OS_SHORT_OD1_RATIO
	,LOAN_OS_SHORT_OD2_RATIO = t1.LOAN_OS_SHORT_OD2_RATIO
	,LOAN_OS_SHORT_OD12_RATIO = t1.LOAN_OS_SHORT_OD12_RATIO
	,LOAN_OS_SHORT_OD345_RATIO = t1.LOAN_OS_SHORT_OD345_RATIO
	,LOAN_OS_MEDIUM_OD1_TOTAL_RATIO = t1.LOAN_OS_MEDIUM_OD1_TOTAL_RATIO
	,LOAN_OS_MEDIUM_OD2_TOTAL_RATIO = t1.LOAN_OS_MEDIUM_OD2_TOTAL_RATIO
	,LOAN_OS_MEDIUM_OD12_TOTAL_RATIO = t1.LOAN_OS_MEDIUM_OD12_TOTAL_RATIO
	,LOAN_OS_MEDIUM_OD345_TOTAL_RATIO = t1.LOAN_OS_MEDIUM_OD345_TOTAL_RATIO
	,LOAN_OS_MEDIUM_OD1_RATIO = t1.LOAN_OS_MEDIUM_OD1_RATIO
	,LOAN_OS_MEDIUM_OD2_RATIO = t1.LOAN_OS_MEDIUM_OD2_RATIO
	,LOAN_OS_MEDIUM_OD12_RATIO = t1.LOAN_OS_MEDIUM_OD12_RATIO
	,LOAN_OS_MEDIUM_OD345_RATIO = t1.LOAN_OS_MEDIUM_OD345_RATIO
	,LOAN_OS_LONG_OD1_TOTAL_RATIO = t1.LOAN_OS_LONG_OD1_TOTAL_RATIO
	,LOAN_OS_LONG_OD2_TOTAL_RATIO = t1.LOAN_OS_LONG_OD2_TOTAL_RATIO
	,LOAN_OS_LONG_OD12_TOTAL_RATIO = t1.LOAN_OS_LONG_OD12_TOTAL_RATIO
	,LOAN_OS_LONG_OD345_TOTAL_RATIO = t1.LOAN_OS_LONG_OD345_TOTAL_RATIO
	,LOAN_OS_LONG_OD1_RATIO = t1.LOAN_OS_LONG_OD1_RATIO
	,LOAN_OS_LONG_OD2_RATIO = t1.LOAN_OS_LONG_OD2_RATIO
	,LOAN_OS_LONG_OD12_RATIO = t1.LOAN_OS_LONG_OD12_RATIO
	,LOAN_OS_LONG_OD345_RATIO = t1.LOAN_OS_LONG_OD345_RATIO
	,LOAN_OS_OTHER_OD1_TOTAL_RATIO = t1.LOAN_OS_OTHER_OD1_TOTAL_RATIO
	,LOAN_OS_OTHER_OD2_TOTAL_RATIO = t1.LOAN_OS_OTHER_OD2_TOTAL_RATIO
	,LOAN_OS_OTHER_OD12_TOTAL_RATIO = t1.LOAN_OS_OTHER_OD12_TOTAL_RATIO
	,LOAN_OS_OTHER_OD345_TOTAL_RATIO = t1.LOAN_OS_OTHER_OD345_TOTAL_RATIO
	,LOAN_OS_OTHER_OD1_RATIO = t1.LOAN_OS_OTHER_OD1_RATIO
	,LOAN_OS_OTHER_OD2_RATIO = t1.LOAN_OS_OTHER_OD2_RATIO
	,LOAN_OS_OTHER_OD12_RATIO = t1.LOAN_OS_OTHER_OD12_RATIO
	,LOAN_OS_OTHER_OD345_RATIO = t1.LOAN_OS_OTHER_OD345_RATIO
FROM session.cic_variables_part2 AS t1
WHERE CIC_FEATURE_STORE_KHCN.MA_CIC = t1.ma_cic AND CIC_FEATURE_STORE_KHCN.MSPHIEU = t1.msphieu AND CIC_FEATURE_STORE_KHCN.RPT_DT = t1.rpt_dt;

COMMIT;

END
