CREATE OR REPLACE PROCEDURE CIC_RB06_DUNO_VAMC_LANVH (IN start_date DATE, IN end_date DATE)
LANGUAGE SQL
BEGIN
   -- Drop the temporary table if it exists
   DROP TABLE IF EXISTS SESSION.tmp_rb06_vamc;


DECLARE GLOBAL TEMPORARY TABLE SESSION.tmp_rb06_vamc 
   (
       RPT_DT VARCHAR(50), MSPHIEU VARCHAR(20), MA_CIC VARCHAR(50), NOGOC_CONLAI VARCHAR(200), MA_TCTD VARCHAR(100), MID_RATE DECIMAL(24, 12)
   ) WITH REPLACE ON
COMMIT PRESERVE ROWS;


INSERT INTO   SESSION.tmp_rb06_vamc
   SELECT DISTINCT 
       a.RPT_DT, a.MSPHIEU, a.MA_CIC, a.NOGOC_CONLAI, a.MA_TCTD,(SELECT MID_RATE
FROM CSO.FCC_CYTB_RATES_HISTORY_OFFICIAL
WHERE CCY1 = 'USD'
AND RATE_DATE <= CAST(a.RPT_DT AS DATE)
ORDER BY RATE_DATE DESC 
        FETCH FIRST 1 ROWS ONLY) AS MID_RATE
FROM CSO.CIC_RB06_DUNO_VAMC a
WHERE TO_DATE(a.RPT_DT, 'YYYYMMDD') BETWEEN start_date AND end_date;


DROP TABLE IF EXISTS SESSION.tmp_CIC_RB06_DUNO_VAMC;


DECLARE GLOBAL TEMPORARY TABLE SESSION.tmp_CIC_RB06_DUNO_VAMC AS (WITH t1 AS(
SELECT a.*, COALESCE(CAST(b.TONG_VND AS DECIMAL(18, 2)), 0.0) + COALESCE(CAST(b.TONG_USD AS DECIMAL(18, 2)), 0.0) * a.MID_RATE AS TONG_DU_NO
FROM SESSION.tmp_rb06_vamc a
LEFT JOIN 
   CSO.CIC_RB06_CTNV b 
ON 
   a.RPT_DT = b.RPT_DT
AND a.MA_CIC = b.MA_CIC
AND a.MSPHIEU = b.MSPHIEU)
SELECT t1.RPT_DT, t1.MSPHIEU, t1.MA_CIC, COALESCE(CAST(t1.NOGOC_CONLAI AS DECIMAL(18, 2)), 0.0) AS NOGOC_CONLAI, COUNT(*) OVER (PARTITION BY t1.RPT_DT, t1.MA_CIC, t1.MA_TCTD) AS VAMC_TCTD_CNT, SUM(NOGOC_CONLAI) OVER () AS VAMC_OS, CASE 
       WHEN t1.TONG_DU_NO <> 0 THEN 
           t1.NOGOC_CONLAI / NULLIF(t1.TONG_DU_NO, 0)
ELSE 
           NULL
END AS VAMC_TO_CURRENT_OS_RATIO
FROM t1)
  WITH DATA ORGANIZE BY ROW;


UPDATE TPBRM1.CIC_FEATURE_STORE_KHCN x
SET   x.VAMC_TCTD_CNT = y.VAMC_TCTD_CNT, x.VAMC_OS = y.VAMC_OS, x.VAMC_TO_CURRENT_OS_RATIO = y.VAMC_TO_CURRENT_OS_RATIO
FROM SESSION.tmp_CIC_RB06_DUNO_VAMC y
WHERE x.RPT_DT = y.RPT_DT
AND x.MSPHIEU = y.MSPHIEU
AND x.MA_CIC = y.MA_CIC;

-- CLEAR TMP
DROP TABLE IF EXISTS SESSION.tmp_rb06_vamc;


DROP TABLE IF EXISTS SESSION.tmp_CIC_RB06_DUNO_VAMC;


COMMIT;

END
