--3. Bảng CSO.CIC_RB06_HDTD
-- Số hợp đồng mở mới, Số hợp đồng đóng, Số hợp đồng đóng tới 3,6,12,24 tháng
SELECT TO_DATE(RPT_DT, 'YYYYMMDD') as RPT_DT, MA_CIC,
  COUNT(CASE WHEN TO_DATE(NGAYKY_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 3 MONTHS THEN 1 END) AS CT_OPEN_L3M,
  COUNT(CASE WHEN TO_DATE(NGAYKY_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 6 MONTHS THEN 1 END) AS CT_OPEN_L6M,
  COUNT(CASE WHEN TO_DATE(NGAYKY_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 12 MONTHS THEN 1 END) AS CT_OPEN_L12M,
  COUNT(CASE WHEN TO_DATE(NGAYKY_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 24 MONTHS THEN 1 END) AS CT_OPEN_L24M,
  
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 3 MONTHS THEN 1 END) AS CT_CLOSE_L3M,
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 6 MONTHS THEN 1 END) AS CT_CLOSE_L6M,
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 12 MONTHS THEN 1 END) AS CT_CLOSE_L12M,
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') >= TO_DATE(RPT_DT, 'YYYYMMDD') - 24 MONTHS THEN 1 END) AS CT_CLOSE_L24M,
  
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') <= TO_DATE(RPT_DT, 'YYYYMMDD') + 3 MONTHS THEN 1 END) AS CT_CLOSE_N3M,
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') <= TO_DATE(RPT_DT, 'YYYYMMDD') + 6 MONTHS THEN 1 END) AS CT_CLOSE_N6M,
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') <= TO_DATE(RPT_DT, 'YYYYMMDD') + 12 MONTHS THEN 1 END) AS CT_CLOSE_N12M,
  COUNT(CASE WHEN TO_DATE(NGAYKT_HDTD, 'YYYYMMDD') <= TO_DATE(RPT_DT, 'YYYYMMDD') + 24 MONTHS THEN 1 END) AS CT_CLOSE_N24M
FROM CSO.CIC_RB06_HDTD
GROUP BY RPT_DT, MA_CIC;

