CREATE TABLE CIC_PROCEDURE_LOG (
    PROCEDURE_NAME VARCHAR(50),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    DURATION_MIN DECIMAL(10, 2)
);


CREATE OR REPLACE PROCEDURE CIC_LOG_PROCEDURE_RUN(
    IN procedure_name VARCHAR(50),
    IN start_time TIMESTAMP,
    IN end_time TIMESTAMP
)
LANGUAGE SQL
BEGIN
    DECLARE duration_min DECIMAL(10, 2);
    SET duration_min = TIMESTAMPDIFF(4, CHAR(end_time - start_time)) / 60.0;
    INSERT INTO CIC_PROCEDURE_LOG (PROCEDURE_NAME, START_TIME, END_TIME, DURATION_MIN)
    VALUES (procedure_name, start_time + 7 HOUR, end_time + 7 HOUR, duration_min);
END;

