-- Switch to the appropriate database (replace TargetDatabaseName with your actual database name)
USE [TargetDatabaseName];
GO

-- Drop synonyms
DROP SYNONYM IFRS9_CST_LN;
DROP SYNONYM IFRS9_COLLATERAL;
DROP SYNONYM IFRS9_CST_CC;
DROP SYNONYM IFRS9_CST_CC_TXN;
DROP SYNONYM IFRS9_CTR_CC;
DROP SYNONYM IFRS9_CTR_CL;
DROP SYNONYM IFRS9_CTR_LC;
DROP SYNONYM IFRS9_CTR_OD;
DROP SYNONYM IFRS9_CUST_INFO;
DROP SYNONYM IFRS9_DEP_AMT;
DROP SYNONYM IFRS9_DEP_AMT_TXN;
DROP SYNONYM IFRS9_LIMIT;
DROP SYNONYM EXCHANGE_RATE;

DROP SYNONYM CL020;
DROP SYNONYM VISA028_CLEAN;
DROP SYNONYM VISA031_SV;
DROP SYNONYM MIS076;
DROP SYNONYM MIS035B;
GO


CREATE SYNONYM IFRS9_CST_LN FOR [DMT]..[IFRS9_CST_LN];
CREATE SYNONYM IFRS9_COLLATERAL FOR [DMT]..[IFRS9_COLLATERAL];
CREATE SYNONYM IFRS9_CST_CC FOR [DMT]..[IFRS9_CST_CC];
CREATE SYNONYM IFRS9_CST_CC_TXN FOR [DMT]..IFRS9_CST_CC_TXN;
CREATE SYNONYM IFRS9_CTR_CC FOR [DMT]..IFRS9_CTR_CC;
CREATE SYNONYM IFRS9_CTR_CL FOR [DMT]..IFRS9_CTR_CL;
CREATE SYNONYM IFRS9_CTR_LC FOR [DMT]..IFRS9_CTR_LC;
CREATE SYNONYM IFRS9_CTR_OD FOR [DMT]..IFRS9_CTR_OD;
CREATE SYNONYM IFRS9_CUST_INFO FOR [DMT]..IFRS9_CUST_INFO;
CREATE SYNONYM IFRS9_DEP_AMT FOR [DMT]..IFRS9_DEP_AMT;
CREATE SYNONYM IFRS9_DEP_AMT_TXN FOR [DMT]..IFRS9_DEP_AMT_TXN;
CREATE SYNONYM IFRS9_LIMIT FOR [DMT]..IFRS9_LIMIT;
CREATE SYNONYM EXCHANGE_RATE FOR [DMT]..EXCHANGE_RATE;


CREATE SYNONYM CL020 FOR [DATA]..CL020;
CREATE SYNONYM VISA028_CLEAN FOR [DATA]..VISA028_CLEAN;
CREATE SYNONYM VISA031_SV FOR [DATA]..VISA031_SV;
CREATE SYNONYM MIS076 FOR [DATA]..MIS076;
CREATE SYNONYM MIS035B FOR [DATA]..MIS035B;