source_table: 'DMT.VW_IFRS9_CST_CC_TXN'
target_table: 'IFRS9_CST_CC_TXN'
source_columns: 
  - PROCESS_DATE
  - CUSTOMER_ID
  - CYCLE_END_DATE
  - BAL_AT_CYCLE_END
  - BAL_AT_END_MONTH
  - GROSS_PAYMENT_LAGGED
  - GROSS_PAYMENT_INMONTH
  - GROSS_PAYMENT_LAGGED_1M
  - AVG_CC_PMT_VS_STM_BAL
  - AVG_CC_AMT
  - NBR_USED_CC
  - MTH_SNC_10DPD_DT_L6
  - MTH_SNC_30DPD_DT_L6
  - MTH_SNC_60DPD_DT_L6
  - MTH_SNC_90DPD_DT_L6
  - MTH_SNC_10DPD_L6
  - MTH_SNC_30DPD_L6
  - MTH_SNC_60DPD_L6
  - MTH_SNC_90DPD_L6
  - NUM_TM_10DPD_L6
  - NUM_TM_30DPD_L6
  - NUM_TM_60DPD_L6
  - NUM_TM_90DPD_L6
  - AVG_UTIL_CC_RATE
  - AVG_UTIL_CC_RATE_L3M
  - AVG_UTIL_CC_RATE_L6M
  - NBR_TXN_CC
  - NBR_TXN_CC_L3M
  - NBR_TXN_CC_L6M
  - NBR_CASH_TXN
  - NBR_CASH_TXN_L3M
  - NBR_CASH_TXN_L6M
  - CASH_TXN_RT
  - CASH_TXN_L3M_RT
  - CASH_TXN_L6M_RT
  - NBR_POS_TXN
  - NBR_POS_TXN_L3M
  - NBR_POS_TXN_L6M
  - POS_TXN_RT
  - POS_TXN_L3M_RT
  - POS_TXN_L6M_RT
  - NBR_ONL_TXN
  - NBR_ONL_TXN_L3M
  - NBR_ONL_TXN_L6M
  - ONL_TXN_RT
  - ONL_TXN_L3M_RT
  - ONL_TXN_L6M_RT
  - CASH_AMT_TXN_L3M
  - CASH_AMT_TXN_L6M
  - POS_AMT_TXN_L3M
  - POS_AMT_TXN_L6M
  - ONL_AMT_TXN_L3M
  - ONL_AMT_TXN_L6M
  - CASH_AMT_TXN
  - POS_AMT_TXN
  - ONL_AMT_TXN
source_date_column: 'PROCESS_DATE'
target_columns: 
target_date_column: 'PROCESS_DATE'
target_data_types: 