source_table: 'DMT.VW_IFRS9_DEP_AMT_TXN'
target_table: 'IFRS9_DEP_AMT_TXN'
source_columns: 
  - RPT_DT_DIM_ID
  - PROCESS_DATE
  - MONTH_ID
  - CST_DIM_ID
  - CUSTOMER_ID
  - TXN_AMT
  - TXN_AMT_L3M
  - AVG_TXN_AMT_L1M
  - AVG_TXN_AMT_L3M
  - AVG_TXN_AMT_L1M_VS_L3M
  - CASH_TXN_AMT
  - CASH_TXN_AMT_L3M
  - AVG_CASH_VS_TXN_AMT_L1M
  - AVG_CASH_VS_TXN_AMT_L3M
  - AVG_CASH_TXN_AMT_PER_TIME_L3M
  - EBANK_TXN_AMT
  - AVG_EBANK_TXN_AMT_L3M
  - AVG_SAL_TXN_AMT_L3M
  - MIN_SAL_TXN_AMT_L3M
  - CASH_CR_TXN_AMT
  - CASH_CR_TXN_AMT_L3M
  - CASH_DR_TXN_AMT
  - CASH_DR_TXN_AMT_L3M
  - AVG_CASH_CR_TXN_AMT_L3M
  - AVG_CASH_DR_TXN_AMT_L3M
  - CR_TXN_AMT
  - CR_TXN_AMT_L3M
  - DR_TXN_AMT
  - DR_TXN_AMT_L3M
  - NET_FLOW_TXN_AMT
  - MAX_NET_FLOW_TXN_AMT_L3M
  - AVG_CASH_CR_TXN_AMT_COVR_L3M
  - AVG_CR_TXN_AMT_VS_OS_L3M
  - SERVICE_AMT
  - MIN_SERVICE_AMT_L3M
  - NUM_CASH_TXN
  - NUM_NON_CASH_TXN
  - TOTAL_NUM_TXN
  - TOTAL_NUM_TXN_L3M
  - TOTAL_NUM_NON_CASH_TXN_L3M
  - AVG_NUM_NON_CASH_TXN_CVR_L3M
source_date_column: 'PROCESS_DATE'
target_columns: 
target_date_column: 'PROCESS_DATE'
target_data_types: 
