source_table: 'DMT.VW_IFRS9_CST_LN'
target_table: 'IFRS9_CST_LN'
source_columns: 
  - RPT_DT_DIM_ID
  - CST_DIM_ID
  - CUSTOMER_ID
  - PROCESS_DATE
  - OS_ONBS
  - OS_ONBS_L3M
  - OS_ONBS_L6M
  - AVG_OS_ONBS
  - AVG_OS_ONBS_L3M
  - AVG_OS_ONBS_L6M
  - OS
  - OS_L3M
  - OS_L6M
  - AVG_OS
  - AVG_OS_L3M
  - AVG_OS_L6M
  - OS_REVL
  - OS_NON_REVL
  - OS_REVL_L6M
  - OS_NON_REVL_L6M
  - AVG_OS_REVL
  - AVG_OS_NON_REVL
  - AVG_OS_REVL_L6M
  - AVG_OS_NON_REVL_L6M
  - MAX_OS_ONBS_L6M
  - VOL_OS_L6M
  - NUM_CR_PRODUCT
  - NUM_CR_PRODUCT_L3M
  - MTH_DBT_SVC
  - MTH_DBT_SVC_L3M
  - MTH_DBT_SVC_L6M
  - MOB
  - IS_MOB_6M
  - CNT_MTH_ONBS_L3M
  - CNT_MTH_ONBS_L6M
  - CNT_MTH_ONBS_L12M
  - COLL_VAL
  - COLL_VAL_CTR
  - TOTAL_COLL_L3M
  - TOTAL_COLL_CTR_L3M
  - AVG_COLL_COVR_OS_ONBS_L3M
  - CUST_LMT
  - COLL_COVR_LMT
  - AVG_OS_ONBS_UTIL_L3M
  - REVL_UTL_RT
  - AVG_REVL_UTL_RT_L3M
  - REVL_LMT
  - OS_BOND
  - OS_BOND_L3M
  - OS_BOND_L6M
  - AVG_OS_BOND
  - AVG_OS_BOND_L3M
  - AVG_OS_BOND_L6M
  - OS_MM
  - OS_MM_L3M
  - OS_MM_L6M
  - AVG_OS_MM
  - AVG_OS_MM_L3M
  - AVG_OS_MM_L6M
  - OS_NON_ONBS
  - OS_NON_ONBS_L3M
  - OS_NON_ONBS_L6M
  - AVG_OS_NON_ONBS
  - AVG_OS_NON_ONBS_L3M
  - AVG_OS_NON_ONBS_L6M
source_date_column: 'PROCESS_DATE'
target_columns: 
target_date_column: 'PROCESS_DATE'
target_data_types: 
