source_table: 'DMT.VW_IFRS9_COLLATERAL'
target_table: 'IFRS9_COLLATERAL'
source_columns: 
  - RPT_DT_DIM_ID
  - PROCESS_DATE
  - CST_DIM_ID
  - CUSTOMER_ID
  - CLT_DIM_ID
  - COLLATERAL_ID
  - COLLATERAL_TP
  - COLLATERAL_CATEGORY_CODE
  - COLLATERAL_CATEGORY_DESC
  - DESCRIPTION
  - TINH_THANH
  - CCY_DIM_ID
  - CCY
  - COLL_VAL
  - COLL_VAL_TPB
  - ORG_DT
  - LAST_DT
  - REVISION_DATE
  - EXPIRE_DATE
  - MATURITY_DATE
  - CUSTOMER_SHARE
  - CUST_SHARE_VALUE
  - COLLATERAL_AGE
  - COLLATERAL_STATUS
  - UNDER_CONSTRUCTION
  - COVENANT_NAME
  - HAIRCUT
  - LIMIT_CTB
  - RI_TYPE_ID
source_date_column: 'PROCESS_DATE'
target_columns: 
target_date_column: 'PROCESS_DATE'
target_data_types: 